#ifndef GRIDTEXT_TYPES_H
#define GRIDTEXT_TYPES_H

/* By naming this file <package-name>_types.h, we can make sure
 * it is automatically included in the autogenerated RcppExports.cpp.
 */


#include "layout.h"

// node list (vector of pointers to layout nodes)
typedef shared_ptr<LayoutNode> NodePtr;
typedef vector<NodePtr > NodeList;

#endif
