# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unit_pt <- function(x) {
    .Call(`_gridtext_unit_pt`, x)
}

gpar_empty <- function() {
    .Call(`_gridtext_gpar_empty`)
}

text_grob <- function(label, x_pt = 0L, y_pt = 0L, gp = NULL, name = NULL) {
    .Call(`_gridtext_text_grob`, label, x_pt, y_pt, gp, name)
}

set_grob_coords <- function(grob, x, y) {
    .Call(`_gridtext_set_grob_coords`, grob, x, y)
}

test_hbox <- function(grobs, widths, box_width, x, y, vspacing, hspacing) {
    .Call(`_gridtext_test_hbox`, grobs, widths, box_width, x, y, vspacing, hspacing)
}

