# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bl_make_grob_box <- function(grob, width_pt) {
    .Call(`_gridtext_bl_make_grob_box`, grob, width_pt)
}

bl_make_hbox <- function(nodes, vspacing_pt, hspacing_pt) {
    .Call(`_gridtext_bl_make_hbox`, nodes, vspacing_pt, hspacing_pt)
}

bl_make_node_list <- function(nodes) {
    .Call(`_gridtext_bl_make_node_list`, nodes)
}

bl_calc_layout <- function(node, width_pt, height_pt = 0) {
    invisible(.Call(`_gridtext_bl_calc_layout`, node, width_pt, height_pt))
}

bl_render <- function(node, x_pt, y_pt) {
    .Call(`_gridtext_bl_render`, node, x_pt, y_pt)
}

grid_renderer <- function() {
    .Call(`_gridtext_grid_renderer`)
}

grid_renderer_text <- function(gr, label, x, y, color = "#000000", fontsize = 12, fontface = "plain", fontfamily = "") {
    invisible(.Call(`_gridtext_grid_renderer_text`, gr, label, x, y, color, fontsize, fontface, fontfamily))
}

grid_renderer_rect <- function(gr, x, y, width, height, color = "#000000", fill = NA_character_, linetype = 1L, linewidth = 1, r = 0L, linejoin = "round", linemitre = 1) {
    invisible(.Call(`_gridtext_grid_renderer_rect`, gr, x, y, width, height, color, fill, linetype, linewidth, r, linejoin, linemitre))
}

grid_renderer_collect_grobs <- function(gr) {
    .Call(`_gridtext_grid_renderer_collect_grobs`, gr)
}

unit_pt <- function(x) {
    .Call(`_gridtext_unit_pt`, x)
}

gpar_empty <- function() {
    .Call(`_gridtext_gpar_empty`)
}

text_grob <- function(label, x_pt = 0L, y_pt = 0L, gp = NULL, name = NULL) {
    .Call(`_gridtext_text_grob`, label, x_pt, y_pt, gp, name)
}

rect_grob <- function(x_pt = 0L, y_pt = 0L, width_pt = 0L, height_pt = 0L, gp = NULL, name = NULL) {
    .Call(`_gridtext_rect_grob`, x_pt, y_pt, width_pt, height_pt, gp, name)
}

roundrect_grob <- function(x_pt = 0L, y_pt = 0L, width_pt = 0L, height_pt = 0L, r_pt = 5L, gp = NULL, name = NULL) {
    .Call(`_gridtext_roundrect_grob`, x_pt, y_pt, width_pt, height_pt, r_pt, gp, name)
}

set_grob_coords <- function(grob, x, y) {
    .Call(`_gridtext_set_grob_coords`, grob, x, y)
}

test_grid_renderer <- function() {
    .Call(`_gridtext_test_grid_renderer`)
}

test_hbox <- function(grobs, widths, box_width, x, y, vspacing, hspacing) {
    .Call(`_gridtext_test_hbox`, grobs, widths, box_width, x, y, vspacing, hspacing)
}

